### ISSUE TITLE
Update reduced CA3 model of Pinsky and Rinzel 1994

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/Contribute#2]
Brief description
============

The 2 compartment model of a CA3 pyramidal neuron of Pinsky and Rinzel [has been partially converted to LEMS](https://github.com/OpenSourceBrain/PinskyRinzelModel/tree/master/NeuroML2). This needs to be checked and matched against the XPP version of the model from ModelDB.

Expected result
============

The version of the model in LEMS is [here](https://github.com/OpenSourceBrain/PinskyRinzelModel/blob/master/NeuroML2/PinskyRinzelCA3CompType.xml). This runs successfully using jNeuroML (using the [LEMS simulation file](https://github.com/OpenSourceBrain/PinskyRinzelModel/blob/master/NeuroML2/Run_PinskyRinzel.xml)), but does not match the [original XPP version of the model](http://senselab.med.yale.edu/ModelDB/ShowModel.asp?model=35358&file=\b04feb12\booth_bose.ode):

![selection_160](https://cloud.githubusercontent.com/assets/1556687/5900566/a08e632a-a562-11e4-8cca-cd32bb537cb7.png)

or the [NEURON version](http://senselab.med.yale.edu/ModelDB/ShowModel.asp?model=35358&file=\b04feb12\batch_a.hoc):

![selection_161](https://cloud.githubusercontent.com/assets/1556687/5900579/cd35537a-a562-11e4-9ddb-2588ebdc1ddf.png)

Suggested steps
=============

Read [Pinsky and Rinzel 1994](http://dx.doi.org/10.1007/BF00962717).

Read the [LEMS/NML2 paper](http://journal.frontiersin.org/Journal/10.3389/fninf.2014.00079/abstract).

Install [XPP](http://www.math.pitt.edu/~bard/xpp/xpp.html) and get the [original XPP version of the model](http://senselab.med.yale.edu/ModelDB/ShowModel.asp?model=35358&file=\b04feb12\booth_bose.ode) running locally.

Get a [GitHub account](join) and sign up to [OSB](http://opensourcebrain.org/account/register).

Fork [the OSB project](https://github.com/OpenSourceBrain/PinskyRinzelModel) to your own GitHub repository.

Investigate differences between the behaviour of this model and the LEMS version by removing channels in each and looking at the traces for membrane potential, [Ca2+] and channel variables.

When the current LEMS simulation is matching, issue a [pull request](https://help.github.com/articles/using-pull-requests/) for it to be checked/merged.

Implement LEMS simulations reproducing Figures 2 and 3 from the paper.

Possible extensions
===================

Reimplement the model as a 2 segment `<cell>` based model and use individual `<ionChannel>` NeuroML files for the channels. An example of this is here: https://github.com/OpenSourceBrain/ACnet2/blob/master/neuroConstruct/generatedNeuroML2/bask.cell.nml

Knowledge prerequisites
===================

Some experience with computational neuroscience and compartmental modelling would be useful.

To be learned
===========

[NeuroML2 & LEMS](http://www.neuroml.org/lems_dev)

Mentor
======

Contact p.gleeson at ucl.ac.uk if you are interested in contributing to this task

**Comment by pgleeson** [comment]
@JustasB will work on this.

**Comment by JustasB** [comment]
The XPP model does not contain a parameter for varying gNMDR that is referenced in the paper for figures 2B-E. No other, unaccounted for, parameters that could be the gNMDR parameter were in the XPP model, suggesting the provided XPP code maybe incomplete.

**Comment by pgleeson** [comment]
Note from the ModelDB readme: "The booth_bose.ode provided here is slightly modified from the original obtained from Victoria Booth's home page; the originals include more extensive simulations: http://www.math.njit.edu/~vbooth/".

I'll look into obtaining these, but the expression for gNMDA (and gAMPA) will need to be incorportated into the LEMS definition for the ComponentType...

**Comment by JustasB** [comment]
Padraig, let me know if you heard anything from Victoria about the missing model elements. Also, Sharon mentioned that you may have some ideas about how to convert this model into two compartments. Specifically, what to do with the surface area proportion and the coupling constant.

**Comment by JustasB** [comment]
Also, I would like to track these items as issues in the PinkyRinsel model, but the issues tab is not enabled. Will you enable it, please?

**Comment by JustasB** [comment]
Also, please enable the wiki on the project.

**Comment by borismarin** [comment]
On 25 May 2015 at 17:56, Justas Birgiolas <notifications@github.com> wrote:

> Also, please enable the wiki on the project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceBrain/Contribute/issues/2#issuecomment-105269132>
> .
>

Done.

**Comment by JustasB** [comment]
Thank you!

**Comment by JustasB** [comment]
Update: I was able to work out the equations for the missing synaptic dynamics, and got them working in the XPP model. Now working on converting them into LEMS.

**Comment by JustasB** [comment]
XPP model changes in https://github.com/OpenSourceBrain/PinskyRinzelModel/pull/3

**Comment by JustasB** [comment]
Created pull request for Figure 2 B & E in LEMS. Next is to convert dimensions to real units.

https://github.com/OpenSourceBrain/PinskyRinzelModel/pull/4

**Comment by JustasB** [comment]
Correct dimensions implemented here: https://github.com/OpenSourceBrain/PinskyRinzelModel/pull/8

**Comment by JustasB** [comment]
Started to work on converting to multi-compartment model.

**Comment by JustasB** [comment]
I've extracted one channel into a separate component and got one figure to work as before.

However, I'm not sure if I'm on the right track. @pgleeson, can you let me know if what I have so far will work for you?

The changes can be seen here (mostly the first few pages of pinskyRinzelCA3Cell2comp.xml):
https://github.com/OpenSourceBrain/PinskyRinzelModel/pull/9

**Comment by pgleeson** [comment]
Good start, but a better approach might be the following:

- Use a modified version of the comptype definition in [cell](https://github.com/NeuroML/NeuroML2/blob/master/NeuroML2CoreTypes/Cells.xml#L782) as the basis for a new compType: twoCompartmentCell.

- Create a new file with a Component for the Na channel (and others) using the standard [NML2 channel definition CompTypes](https://neuroml.org/NeuroML2CoreTypes/Channels.html#ionChannelHH), e.g.
https://github.com/OpenSourceBrain/GranuleCell/blob/master/neuroConstruct/generatedNeuroML2/Gran_H_98.channel.nml
https://github.com/OpenSourceBrain/GranuleCell/blob/master/neuroConstruct/generatedNeuroML2/Gran_KCa_98.channel.nml

- You should then be able to create a Component for the new cell along the lines of: 
```
      <twoCompartmentCell id="...">
        <notes>...</notes>
        <morphology id="morphology">
            <segment id="0" name="soma">
                <proximal x="0.0" y="0.0" z="0.0" diameter="40.0"/>
                <distal x="0.0" y="40.0" z="0.0" diameter="40.0"/>
            </segment>
            <segment id="1" name="dend">
                <parent segment="0"/>
                <proximal x="0.0" y="40.0" z="0.0" diameter="2.0"/>
                <distal x="0.0" y="200.0" z="0.0" diameter="2.0"/>
            </segment>
            <segmentGroup id="soma_group">
		<member segment="0"/>
            </segmentGroup>
            <segmentGroup id="dend_group">
		<member segment="1"/>
            </segmentGroup>
        </morphology>
        <biophysicalProperties id="biophys">
            <membraneProperties>
                <channelDensity condDensity="?? mS_per_cm2" id="Na_all" ionChannel="Na" ion="na" erev="55.0 mV" segmentGroup="soma_group"/>
                <!-- More channels... -->
                <spikeThresh value="0 mV"/>
                <specificCapacitance value="1.0 uF_per_cm2"/>
                <initMembPotential value="-65.0 mV"/>
            </membraneProperties>
            <intracellularProperties>
                <species id="ca" ion="ca" concentrationModel="CaPool" initialConcentration="7.55E-11 mol_per_cm3" initialExtConcentration="2.4E-6 mol_per_cm3"/>
                <resistivity value="0.1 kohm_cm"/>
            </intracellularProperties>
        </biophysicalProperties>
    </twoCompartmentCell>
```
- In the first version of twoCompartmentCell based on cell, only the soma v will be calculated from the channel densities on the cell, so compare the behaviour of a pinskyRinzelCA3Cell with p=1 (i.e. soma only) to a twoCompartmentCell with just channels on the soma.

Hope this is an understandable outline...

**Comment by JustasB** [comment]
Ok, I found enough resources to make the 2-compartment cell. One aspect not clear to me is testing. @pgleeson, jLEMS doesn't support 2-compartment models, what are your thoughts on making sure the model implements what it says it does?

**Comment by pgleeson** [comment]
An intermediate step is just to use the existing  `<cell>` element & just one segment & match that to a pinskyRinzelCA3Cell with p=1, i.e. ignore dendrite completely.

If this works with jnml & jnml -neuron, you could try with a `<cell>` with 2 segments & mapping to Neuron, which does support multicompartmental cells. Then manually modify  `<cell>` ->  `<twoCompartmentCell>` & allow that to run natively in jLEMS by defining a new internal state variable Vd & calculating the currents from the 2nd segment, in the same way that `<cell>` calculates the currents from the soma only...

**Comment by JustasB** [comment]
@pgleeson I'm running into an issue where the select='...' attribute does not appear to be working correctly, and it's preventing me from progressing. I've spent about 1.5 days getting it to work, with no avail. Let me know if you're aware of this issue and if there are any workarounds?

The basic example is with passive channels:

```
<ionChannel id="somaLeak" type="ionChannelPassive" conductance="0 pS" />
<ionChannel id="dendriteLeak" type="ionChannelPassive" conductance="0 pS" />
```
Then in cell declaration (note the segmentGroup values):
```
<membraneProperties>
    <channelDensity id="somaLeakChannels" ionChannel="somaLeak" condDensity="0.1 mS_per_cm2" erev="-60 mV"
    segmentGroup="soma_group" ion="non-specific" />
    
    <channelDensity id="dendriteLeakChannels" ionChannel="dendriteLeak" condDensity="0.1 mS_per_cm2"
    erev="-60 mV" segmentGroup="dendrite_group" ion="non-specific" />
    
    <spikeThresh value="0 mV"/>
    <specificCapacitance value="3.0 uF_per_cm2"/>
    <initMembPotential value="-40.0 mV"/>
</membraneProperties>
```
In new ComponentType twoCompartmentCell, which extends "cell" type (tried with baseCellMembPot too), I extract the soma and dendrite currents separately using the XPath selectors:
```
<DerivedVariable name="iDensitySoma" exposure="iDensitySoma" dimension="currentDensity" select="biophysicalProperties/membraneProperties/channelDensities[segmentGroup='soma_group']/iDensity" reduce="add"/>
            
<DerivedVariable name="iDensityDendrite" exposure="iDensityDendrite" dimension="currentDensity" select="biophysicalProperties/membraneProperties/channelDensities[segmentGroup='dendrite_group']/iDensity" reduce="add"/>
```
Voltage derivs are then computed:
```
<TimeDerivative variable="Vs" value="iDensitySoma/totSpecCap" />
<TimeDerivative variable="Vd" value="iDensityDendrite/totSpecCap" />
```
This is a very simple cell, and when plotted, Vs should start at -40mv and then climb down to -60mv and stay there. However, what happens is that it starts at -40mv and then climbs down to some other value around -50mv. What's bizarre is that if in membraneProperties (1) the segmentGroup values are changed to be identical (ie both say "soma_group") or (2) one (either) of the channels is removed, then the voltage does work correctly, climbing down to -60mv.

This appears to have something to do with the xpath selector in the DerivedVariables. Any ideas what the issue is?

Alternatively, I could probably make this work by adding another type of membraneProperties type (and probably a biophyzProperties type), and grouping the soma/dendrite channels as separate groups of children of the membraneProperties. This, however, would be hacky as the segmentGroup values already provide the same information, and the xpath in the select attribute should do the job.

Let me know your thoughts.

**Comment by pgleeson** [comment]
Could you commit the provisional code so I can have a look & run locally? One option is to define explicitly chanDensities as on soma & on dend (as someone could name the groups anything):


        <Children name="channelDensitiesSoma" type="baseChannelDensity"/>
        <Children name="channelDensitiesDend" type="baseChannelDensity"/>
        ...
        <DerivedVariable name="iDensitySoma" exposure="iDensitySoma" dimension="currentDensity" select="channelDensitiesSoma/iDensity"/>


Also, I'd highly recommend getting a soma only example working first & compared to a cell with p=1 before getting the dendrite involved. 

Lets aim for the end of next week (or before) to wrap up with Pinsky Rinzel (including documentation/wikis etc. ) and move on to https://github.com/OpenSourceBrain/Contribute/issues/6.

cc @scrook

**Comment by JustasB** [comment]
Yes, I would like to move on as well.

I've created the pull request with the contrived example showing the problem. It's here: 
https://github.com/OpenSourceBrain/PinskyRinzelModel/pull/9

Steps to reproduce:
* In 2comp folder, run: ./jnml LEMS_BUG.xml
* Should see a plot for soma and dendrite, starting at -40mv and going to about -50mv.
* Both should go to -60mv (both are passive leak channels with -60mv erev)
* Comment out lines 77-78 in pyramidal2comp.cell.nml (the dendrite leak channel)
* Run jnml again, notice the soma goes to -60mv correctly
* Note in line 80 of cell.nml, iDensitySoma should only get the idensity of soma_group channels, and should be unaffected by addition of channels to other segmentGroups.
* Note lines 84 & 89 do not introduce anything else that should be affected by addition of dendrite_group channel.

Keep in mind that I already got the soma channels to work by themselves (reproducing the XPP model) and dendrite channels by themselves. It's when I try to combine the channels from both segments that these numerical issues come up. The example above is the simplest one. If other channels are uncommented in pyramidal2comp.cell.nml, I get runtime exceptions with very large state variable values (which do not occur if only one segmentGroup value is used in pyramidal2comp.cell.nml).

I'll give the soma/dend channel densities suggestion a try.

**Comment by JustasB** [comment]
Ok, splitting channelDensities by soma/dend is working. I also discovered what the initial problem was. iDensity is being computed from the v variable, and when there are only soma or dend channels, the v would happen to be the same as Vs or Vd. When the channels have different groups, the dendrite and soma channels would continue to be computed using v, which is a result of combination of all channels. I solved this by setting v to Vs and Vd for soma and dendrite channels respectively. I'm able to continue now.

**Comment by JustasB** [comment]
Got the 2-compartment model working, reproducing the XPP figures. All channels in their own files, and using a new type based off baseCellMembPot.

Checked in here: https://github.com/JustasB/PinskyRinzelModel/commit/9bfe1d6ecf034df186f1f11c2bdef255b701d3be

Let me know any changes you'd like me to make.

@pgleeson @scrook

**Comment by pgleeson** [comment]
Completed by @JustasB!
