### ISSUE TITLE
Improve jLEMS GUI interface

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/Contribute#4]
Brief description
============

The GUI interface for [jLEMS](https://github.com/LEMS/jLEMS) (see below) requires some updates to the menu items and options for rerunning the simulations.

![selection_168](https://cloud.githubusercontent.com/assets/1556687/6554361/b1452080-c652-11e4-951d-4ae2804ba9bc.png)

Expected result
============

More details are included here: https://github.com/LEMS/jLEMS/issues/49

Suggested steps
=============

Install jLEMS & get running locally.
Investigate the source code for the application, in particular [StandaloneViewer.java](https://github.com/LEMS/jLEMS/blob/development/src/main/java/org/lemsml/jlems/viz/datadisplay/StandaloneViewer.java)
Fork the [**development branch**](https://github.com/LEMS/jLEMS/tree/development) of the application and make updates/changes.
Issue pull request for updates.

Please **do not make extensive changes or reformat large sections of code** and expect them to be merged. Please keep changes to a minimum until you let us know about them.

Note that [jNeuroML](https://github.com/NeuroML/jNeuroML) uses jLEMS for simulating LEMS models and viewing results, but adds a lot of NeuroML specific features on top of the core jLEMS functionality. jLEMS is intended to be neuroscience independent and so there should be no NeuroML specific features there, though most of the examples have a neuroscience basis. Any updates to jLEMS will get integrated into jNeuroML too, but it's simplest to work with jLEMS alone while updating the GUI.

Knowledge prerequisites
===================

Java GUI development
Reading the [LEMS/NML2 paper](http://journal.frontiersin.org/Journal/10.3389/fninf.2014.00079/abstract) will be a big help for this task

Mentor
======

Contact p.gleeson -at- ucl.ac.uk if you are interested in contributing to this task.

**Comment by hugh-osborne** [comment]
Hi, I'm taking a look at this.

First steps (taken from LEMS/jLEMS#49 and a casual run through):

- Remove 'Save' menu option
- Fix importFile method so it functions as expected
- Set 'Open' to perform importFile method and remove 'Import' from the UI menu
- Create 'Simulation' menu list with re-run and run.. items

I think it would also be useful to have a setting (available as an on/off selection in the menu) to reload the file on re-run for quick editing of the xml in an external text editor and viewing of the results in the simulator.

**Comment by pgleeson** [comment]
That's great @hugh-osborne. 

Good idea regarding the reload file and rerun option. Maybe if you have time, look into key bindings, e.g. press F6 to reload LEMS file & rerun.

**Comment by pgleeson** [comment]
@hugh-osborne any update on progress with this?

**Comment by hugh-osborne** [comment]
@pgleeson 
I've created a separate control panel window to handle opening and re-running. This makes the UI more manageable when dealing with multiple DataViewers and RunConfigs. Open now works, and replaces the current loaded file/simulation. The Reload and Run menu item (with F6 shortcut) will reload the current file and run the simulation again.

I'd like a couple more days to clean the code up. Perhaps then would be a good time for a review? I've a few ideas for how to incorporate setting the time steps and run time etc which we can go over.

![jlems_ui_1](https://cloud.githubusercontent.com/assets/10435430/9694316/69cd175a-534f-11e5-92f7-c1d431b223ca.jpg)

**Comment by pgleeson** [comment]
Thanks for the update @hugh-osborne. Looks good so far. It may be better to just have buttons as opposed to menu items in the control panel window... Fewer clicks.

Also, are you working from the development branch of jLEMS? That's where the latets & most stable version is.

**Comment by pgleeson** [comment]
I've merged these changes into the development branches now. A few last minute updates, mainly for exception handling and informing the user of common errors. Thanks again @hugh-osborne.
