### ISSUE TITLE
Internal Error when viewing model components

### ISSUE THREAD

**Issue by JustasB** [OpenSourceBrain/Contribute#8]
I receive "internal error" message when navigating the following urls:

http://www.opensourcebrain.org/embedded/thalamocortical
http://www.opensourcebrain.org/embedded/l5bpyrcellhayetal2011

The links are obtained by clicking the "Model components" menu item in the following models:
http://www.opensourcebrain.org/projects/45
http://www.opensourcebrain.org/projects/thalamocortical

**Comment by pgleeson** [comment]
These "Model components" menu items shouldn't be there any more. These generated pages have been replaced by the views in the OSB 3D explorer. See https://github.com/OpenSourceBrain/redmine/issues/128.

Btw @JustasB, https://github.com/OpenSourceBrain/redmine/issues is a better place for OSB website specific issues (i.e. tasks for the OSB admins to address)
